[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "taed2_safeagent"
version = "0.0.1"
description = "A short description of the project."
authors = [
  { name = "SafeAgent" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "dvc[s3]>=3.67.1",
    "loguru",
    "mkdocs",
    "mlflow>=3.16.0",
    "pip",
    "python-dotenv",
    "PyYAML==6.0.3",
    "ruff",
    "tqdm",
    "typer",
]
requires-python = "~=3.11.0"


[tool.ruff]
line-length = 99
src = ["taed2_safeagent"]
include = ["pyproject.toml", "taed2_safeagent/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["taed2_safeagent"]
force-sort-within-sections = true

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pylint==4.1.2",
    "pynblint==0.1.6",
    "ruff>=0.16.7",
]
data = [
    "deepchecks==0.19.1",
    "great_expectations==1.23.2",
    "numpy==1.26.4",
    "pandas==2.2.3",
    "scikit-learn==1.5.2",
    "category-encoders==2.6.4",
    "setuptools==80.9.0",
    "typer==0.12.5",
    "click==8.1.8",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = ["integration: checks the full pinned dataset"]

[tool.pylint.main]
py-version = "3.11"

[tool.pylint.format]
max-line-length = 99

[tool.pylint.design]
max-locals = 25

[tool.pylint.messages_control]
disable = ["missing-module-docstring", "missing-function-docstring"]

